workflows:
  default:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Build APK
        script: flutter build apk --release --no-enable-impeller
      - name: Build iOS
        script: flutter build ios --release --no-enable-impeller
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.ipa
