workflows:
  default:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: "3.24.3" # Flutter 버전을 명확히 지정
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean

      # APK 빌드
      - name: Build APK
        script: flutter build apk --release # Impeller 비활성화 플래그 삭제

      # Web 빌드 추가
      - name: Build Flutter Web
        script: flutter build web

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/web/** # 웹 빌드 결과를 아티팩트에 포함
