workflows:
  default:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: "3.24.3" # Flutter 버전을 명확히 지정
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean

      - name: Build APK
        script: flutter build apk --release # Impeller 비활성화 플래그 삭제
      - name: Build iOS
        script: flutter build ios --debug # Impeller 비활성화 플래그 삭제
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.app # Debug 모드로 빌드된 .app 파일을 아티팩트로 저장
#      - build/ios/iphoneos/*.ipa
